---
language: node_js
node_js:
  - "6"

sudo: false

git:
  submodules: false

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower

install:
  - yarn install
  - bower install

# Build to dist so we can use it for the Broccoli tree
# for tests, as if it was passed to the Ember addon

script:
  - ember build
  - npm test
